# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

# setup node
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# install node dependencies and compile with typescript
- script: |
    npm install
    npm run compile
  displayName: 'npm install and compile'

# run test
- script: npx ava --tap | npx tap-xunit > TEST.xml
  displayName: 'ava test runner'

# publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: xUnit
    testResultsFiles: '**/TEST*.xml' 
    failTaskOnFailedTests: true

